spring:
  application:
    name: pedidos-microsservicos-api
  # Configurado RabbitMQ
  rabbitmq:
    host: localhost
    username: rabbitmq
    password: rabbitmq
    port: 5672

#SpringDoc OpenAPI
springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
  packagesToScan: io.github.luizhenriquemaronezi.pedidos_microsservicos_api.controller

#Configurações Customizadas RabbitMQ

rabbitmq:
  exchange:
    name: pedidos.v1.pedido-criado